import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Providers from '@/components/providers'
import Navbar from '@/components/Navbar'
import { Toaster } from '@/components/ui/toaster'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PrepPortal - The best place to prepare for your exams',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className , "antialiased min-h-screen pt-16 ")}>

        <Providers>
          <Navbar />
          {children}
          <Toaster />
        </Providers>
       
      </body>
    </html>
  )
}
